// @generated by protoc-gen-es v2.12.0 with parameter "target=js,import_extension=js"
// @generated from file abutown.proto (package abutown.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file abutown.proto.
 */
export const file_abutown = /*@__PURE__*/
  fileDesc("Cg1hYnV0b3duLnByb3RvEgphYnV0b3duLnYxIhcKBFBpbmcSDwoHbWVzc2FnZRgBIAEoCWIGcHJvdG8z");

/**
 * Describes the message abutown.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema = /*@__PURE__*/
  messageDesc(file_abutown, 0);

