// @generated by protoc-gen-es v2.12.0 with parameter "target=js,import_extension=js"
// @generated from file live.proto (package live.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file live.proto.
 */
export const file_live = /*@__PURE__*/
  fileDesc("CgpsaXZlLnByb3RvEgdsaXZlLnYxIncKDUxpdmVDbGllbnRNc2cSFwoPc3Vic2NyaWJlX2NlbGxzGAEgAygNEhkKEXVuc3Vic2NyaWJlX2NlbGxzGAIgAygNEh0KEHN1YnNjcmliZV92aXRhbHMYAyABKAhIAIgBAUITChFfc3Vic2NyaWJlX3ZpdGFscyJICgxDaXRpemVuU3RhdGUSCgoCaWQYASABKA0SDAoEeF9kbRgCIAEoERIMCgR6X2RtGAMgASgREhAKCGFjdGl2aXR5GAQgASgNIoEBChBDaXRpemVuQ2VsbEZyYW1lEgwKBGNlbGwYASABKA0SEgoKd29ybGRfdGljaxgCIAEoBBIQCghrZXlmcmFtZRgDIAEoCBInCghjaXRpemVucxgEIAMoCzIVLmxpdmUudjEuQ2l0aXplblN0YXRlEhAKCGRlcGFydGVkGAUgAygNIrIBCg1FY29ub215Vml0YWxzEhIKCndvcmxkX3RpY2sYASABKAQSFgoOc19vZl93b3JsZF9kYXkYAiABKA0SEgoKcG9wdWxhdGlvbhgDIAEoBBITCgt0b3RhbF9tb25leRgEIAEoAxIQCghhdWRpdF9vaxgFIAEoDRIkCgZwcmljZXMYBiADKAsyFC5saXZlLnYxLk1hcmtldFByaWNlEhQKDHRyaXBzX2FjdGl2ZRgHIAEoBCJaCgtNYXJrZXRQcmljZRIRCgltYXJrZXRfaWQYASABKA0SDwoHZ29vZF9pZBgCIAEoDRISCgpld21hX3ByaWNlGAMgASgDEhMKC21hcmtldF9uYW1lGAQgASgJIk0KDUJ1aWxkaW5nRGVsdGESFQoNYnVpbGRpbmdfdXVpZBgBIAEoCRIRCglsaWZlY3ljbGUYAiABKA0SEgoKd29ybGRfdGljaxgDIAEoBCKcAQoNTGl2ZVNlcnZlck1zZxIoCgVjZWxscxgBIAMoCzIZLmxpdmUudjEuQ2l0aXplbkNlbGxGcmFtZRIrCgZ2aXRhbHMYAiABKAsyFi5saXZlLnYxLkVjb25vbXlWaXRhbHNIAIgBARIpCglidWlsZGluZ3MYAyADKAsyFi5saXZlLnYxLkJ1aWxkaW5nRGVsdGFCCQoHX3ZpdGFsc2IGcHJvdG8z");

/**
 * Describes the message live.v1.LiveClientMsg.
 * Use `create(LiveClientMsgSchema)` to create a new message.
 */
export const LiveClientMsgSchema = /*@__PURE__*/
  messageDesc(file_live, 0);

/**
 * Describes the message live.v1.CitizenState.
 * Use `create(CitizenStateSchema)` to create a new message.
 */
export const CitizenStateSchema = /*@__PURE__*/
  messageDesc(file_live, 1);

/**
 * Describes the message live.v1.CitizenCellFrame.
 * Use `create(CitizenCellFrameSchema)` to create a new message.
 */
export const CitizenCellFrameSchema = /*@__PURE__*/
  messageDesc(file_live, 2);

/**
 * Describes the message live.v1.EconomyVitals.
 * Use `create(EconomyVitalsSchema)` to create a new message.
 */
export const EconomyVitalsSchema = /*@__PURE__*/
  messageDesc(file_live, 3);

/**
 * Describes the message live.v1.MarketPrice.
 * Use `create(MarketPriceSchema)` to create a new message.
 */
export const MarketPriceSchema = /*@__PURE__*/
  messageDesc(file_live, 4);

/**
 * Describes the message live.v1.BuildingDelta.
 * Use `create(BuildingDeltaSchema)` to create a new message.
 */
export const BuildingDeltaSchema = /*@__PURE__*/
  messageDesc(file_live, 5);

/**
 * Describes the message live.v1.LiveServerMsg.
 * Use `create(LiveServerMsgSchema)` to create a new message.
 */
export const LiveServerMsgSchema = /*@__PURE__*/
  messageDesc(file_live, 6);

