// @generated by protoc-gen-es v2.12.0 with parameter "target=js,import_extension=js"
// @generated from file traffic.proto (package traffic.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file traffic.proto.
 */
export const file_traffic = /*@__PURE__*/
  fileDesc("Cg10cmFmZmljLnByb3RvEgp0cmFmZmljLnYxInYKEFRyYWZmaWNDbGllbnRNc2cSFwoPc3Vic2NyaWJlX2NlbGxzGAEgAygNEhkKEXVuc3Vic2NyaWJlX2NlbGxzGAIgAygNEhsKDnN1YnNjcmliZV9mbG93GAMgASgISACIAQFCEQoPX3N1YnNjcmliZV9mbG93IkIKDFZlaGljbGVTdGF0ZRIKCgJpZBgBIAEoDRIMCgRsYW5lGAIgASgNEgsKA3NfcRgDIAEoDRILCgN2X3EYBCABKA0idwoJQ2VsbEZyYW1lEgwKBGNlbGwYASABKA0SDAoEdGljaxgCIAEoBBIQCghrZXlmcmFtZRgDIAEoCBIqCgh2ZWhpY2xlcxgEIAMoCzIYLnRyYWZmaWMudjEuVmVoaWNsZVN0YXRlEhAKCGRlcGFydGVkGAUgAygNIjUKCUZsb3dTdGF0ZRIMCgRlZGdlGAEgASgNEg0KBWNvdW50GAIgASgNEgsKA3ZfcRgDIAEoDSI/CglGbG93RnJhbWUSDAoEdGljaxgBIAEoBBIkCgVlZGdlcxgCIAMoCzIVLnRyYWZmaWMudjEuRmxvd1N0YXRlImsKEFRyYWZmaWNTZXJ2ZXJNc2cSJAoFY2VsbHMYASADKAsyFS50cmFmZmljLnYxLkNlbGxGcmFtZRIoCgRmbG93GAIgASgLMhUudHJhZmZpYy52MS5GbG93RnJhbWVIAIgBAUIHCgVfZmxvd2IGcHJvdG8z");

/**
 * Describes the message traffic.v1.TrafficClientMsg.
 * Use `create(TrafficClientMsgSchema)` to create a new message.
 */
export const TrafficClientMsgSchema = /*@__PURE__*/
  messageDesc(file_traffic, 0);

/**
 * Describes the message traffic.v1.VehicleState.
 * Use `create(VehicleStateSchema)` to create a new message.
 */
export const VehicleStateSchema = /*@__PURE__*/
  messageDesc(file_traffic, 1);

/**
 * Describes the message traffic.v1.CellFrame.
 * Use `create(CellFrameSchema)` to create a new message.
 */
export const CellFrameSchema = /*@__PURE__*/
  messageDesc(file_traffic, 2);

/**
 * Describes the message traffic.v1.FlowState.
 * Use `create(FlowStateSchema)` to create a new message.
 */
export const FlowStateSchema = /*@__PURE__*/
  messageDesc(file_traffic, 3);

/**
 * Describes the message traffic.v1.FlowFrame.
 * Use `create(FlowFrameSchema)` to create a new message.
 */
export const FlowFrameSchema = /*@__PURE__*/
  messageDesc(file_traffic, 4);

/**
 * Describes the message traffic.v1.TrafficServerMsg.
 * Use `create(TrafficServerMsgSchema)` to create a new message.
 */
export const TrafficServerMsgSchema = /*@__PURE__*/
  messageDesc(file_traffic, 5);

