//! Protobuf-generated types — see `proto/abutown.proto`.
//! Generated by `build.rs` via `prost-build`; output lands in `OUT_DIR`.
//! Reduced to a placeholder when the app was stripped to the card hand.
//!
//! `world.proto` shares `package abutown.v1` with `abutown.proto`; prost
//! merges both files into the same `abutown.v1.rs`, so the world-bake
//! artefact types (WorldManifest, RoadGraph, WorldTile, …) live in `v1`
//! alongside `Ping`. No name collisions — checked 2026-07-06.
pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/abutown.v1.rs"));
}

/// Traffic wire schema — see `proto/traffic.proto`. The winterthur-traffic WS
/// gateway (Task 8) encodes/decodes these; the browser client (Task 9) mirrors
/// them via the buf TS codegen.
pub mod traffic {
    include!(concat!(env!("OUT_DIR"), "/traffic.v1.rs"));
}

/// Live-world wire schema — see `proto/live.proto`. Citizen AOI cell frames,
/// economy vitals, and building lifecycle deltas for the `/live` WS channel
/// (Task 12/13); the browser client mirrors them via the buf TS codegen.
pub mod live {
    include!(concat!(env!("OUT_DIR"), "/live.v1.rs"));
}

/// Wire protocol version. Bump when the next simulation's schema stabilizes.
pub const PROTOCOL_VERSION: u16 = 1;
