//! Protobuf-generated types — see `proto/abutown.proto`.
//! Generated by `build.rs` via `prost-build`; output lands in `OUT_DIR`.
//! Reduced to a placeholder when the app was stripped to the card hand.
pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/abutown.v1.rs"));
}

/// Wire protocol version. Bump when the next simulation's schema stabilizes.
pub const PROTOCOL_VERSION: u16 = 1;
