/// Protobuf-generated types — see `proto/abutown.proto` for the schema.
/// Generated by `build.rs` via `prost-build`; output lands in `OUT_DIR`.
/// Module name matches the proto `package abutown.v1` namespace.
pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/abutown.v1.rs"));
}

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u16 = 1;

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct WorldId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EntityId(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ChunkCoordDto {
    pub x: i32,
    pub y: i32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChunkStateDto {
    Asleep,
    Warm,
    Active,
    Hot,
}

#[derive(Debug, Clone, PartialEq)]
pub struct HealthResponse {
    pub service: String,
    pub world_id: WorldId,
    pub ok: bool,
    pub protocol_version: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub struct WorldSummaryDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub chunk_size: u16,
    pub loaded_chunks: Vec<ChunkCoordDto>,
    pub tick_period_ms: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TileBaseDto {
    Grass,
    Water,
    Riverbank,
    Forest,
    Park,
    Reserve,
    Plaza,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TileSurfaceDto {
    None,
    Street,
    Bridge,
    Rail,
    RailCrossing,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TileCoverDto {
    None,
    Building,
    Tree,
    Detail,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LayeredTileDto {
    pub local_index: u16,
    pub base: TileBaseDto,
    pub surface: TileSurfaceDto,
    pub cover: TileCoverDto,
    pub display: Option<String>,
    pub zone_id: Option<String>,
    pub road_mask: Option<u8>,
    pub rail_mask: Option<u8>,
    pub version: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChunkSnapshotDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub coord: ChunkCoordDto,
    pub chunk_state: ChunkStateDto,
    pub chunk_version: u64,
    pub tile_count: u16,
    pub tiles: Vec<LayeredTileDto>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CommandResponseDto {
    Accepted(CommandAcceptedDto),
    Rejected(CommandRejectedDto),
}

#[derive(Debug, Clone, PartialEq)]
pub struct CommandAcceptedDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub command_id: String,
    pub event: WorldEventDto,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CommandRejectedDto {
    pub protocol_version: u16,
    pub world_id: Option<WorldId>,
    pub command_id: Option<String>,
    pub code: String,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum WorldEventDto {}

#[derive(Debug, Clone, PartialEq)]
pub enum ClientMessageDto {
    ChunkSubscribe(ChunkSubscribeDto),
    ChunkUnsubscribe(ChunkUnsubscribeDto),
}

#[derive(Debug, Clone, PartialEq)]
pub struct ChunkSubscribeDto {
    pub protocol_version: u16,
    pub coords: Vec<ChunkCoordDto>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ChunkUnsubscribeDto {
    pub protocol_version: u16,
    pub coords: Vec<ChunkCoordDto>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServerMessageDto {
    Hello(ServerHelloDto),
    TilePulse(TilePulseDeltaDto),
    MobilityChunkDelta(MobilityChunkDeltaDto),
    MobilityChunkSnapshot(MobilityChunkSnapshotDto),
    WorldEvent { event: WorldEventDto },
    Error(ServerErrorDto),
}

#[derive(Debug, Clone, PartialEq)]
pub struct ServerHelloDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub chunk_size: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub struct TilePulseDeltaDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub tick: u64,
    pub version: u64,
    pub coord: ChunkCoordDto,
    pub local_index: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MobilitySnapshotDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub tick: u64,
    pub agents: Vec<AgentMobilityDto>,
    pub vehicles: Vec<VehicleMobilityDto>,
    pub stops: Vec<StopMobilityDto>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MobilityChunkDeltaDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub tick: u64,
    pub chunk: ChunkCoordDto,
    pub changed_agents: Vec<AgentMobilityDto>,
    pub changed_vehicles: Vec<VehicleMobilityDto>,
    pub left_agents: Vec<EntityId>,
    pub left_vehicles: Vec<EntityId>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct MobilityChunkSnapshotDto {
    pub protocol_version: u16,
    pub world_id: WorldId,
    pub tick: u64,
    pub chunk: ChunkCoordDto,
    pub agents: Vec<AgentMobilityDto>,
    pub vehicles: Vec<VehicleMobilityDto>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct WorldCoordDto {
    pub x: f32,
    pub y: f32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VehicleKindDto {
    Car,
    Tram,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DirectionDto {
    N,
    Ne,
    E,
    Se,
    S,
    Sw,
    W,
    Nw,
}

#[derive(Debug, Clone, PartialEq)]
pub struct AgentMobilityDto {
    pub id: EntityId,
    pub state: AgentMobilityStateDto,
    pub plan_cursor: usize,
    pub world_coord: WorldCoordDto,
    pub direction: DirectionDto,
    pub sprite_key: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum AgentMobilityStateDto {
    AtActivity {
        activity_id: String,
    },
    Walking {
        link_id: String,
        progress: f32,
    },
    WaitingAtStop {
        stop_id: String,
    },
    Boarding {
        vehicle_id: EntityId,
        stop_id: String,
    },
    InVehicle {
        vehicle_id: EntityId,
        seat_index: u16,
    },
    Alighting {
        vehicle_id: EntityId,
        stop_id: String,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub struct VehicleMobilityDto {
    pub id: EntityId,
    pub kind: VehicleKindDto,
    pub route_id: String,
    pub link_index: usize,
    pub progress: f32,
    pub capacity: u16,
    pub occupants: Vec<EntityId>,
    pub dwell_ticks_remaining: u16,
    pub world_coord: WorldCoordDto,
    pub direction: DirectionDto,
    pub sprite_key: String,
}

#[derive(Debug, Clone, PartialEq)]
pub struct StopMobilityDto {
    pub id: String,
    pub route_id: String,
    pub link_index: usize,
    pub progress: f32,
    pub waiting_agents: Vec<EntityId>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ServerErrorDto {
    pub protocol_version: u16,
    pub world_id: Option<WorldId>,
    pub code: String,
    pub message: String,
}

// === proto → DTO conversions at the HTTP/WS inbound boundary ===
//
// Inbound protobuf values are converted at the crate boundary. Errors are
// `(code, message)` so callers can lift them into their own rejection types
// without depending on us.

pub type ProtoConversionError = (&'static str, &'static str);

impl TryFrom<v1::TileBase> for TileBaseDto {
    type Error = ProtoConversionError;

    fn try_from(value: v1::TileBase) -> Result<Self, Self::Error> {
        match value {
            v1::TileBase::Unspecified => Err((
                "invalid_enum",
                "TileBase is UNSPECIFIED; sender must provide a concrete variant",
            )),
            v1::TileBase::Grass => Ok(Self::Grass),
            v1::TileBase::Water => Ok(Self::Water),
            v1::TileBase::Riverbank => Ok(Self::Riverbank),
            v1::TileBase::Forest => Ok(Self::Forest),
            v1::TileBase::Park => Ok(Self::Park),
            v1::TileBase::Reserve => Ok(Self::Reserve),
            v1::TileBase::Plaza => Ok(Self::Plaza),
        }
    }
}

impl From<TileBaseDto> for v1::TileBase {
    fn from(value: TileBaseDto) -> Self {
        match value {
            TileBaseDto::Grass => Self::Grass,
            TileBaseDto::Water => Self::Water,
            TileBaseDto::Riverbank => Self::Riverbank,
            TileBaseDto::Forest => Self::Forest,
            TileBaseDto::Park => Self::Park,
            TileBaseDto::Reserve => Self::Reserve,
            TileBaseDto::Plaza => Self::Plaza,
        }
    }
}

impl TryFrom<v1::TileSurface> for TileSurfaceDto {
    type Error = ProtoConversionError;

    fn try_from(value: v1::TileSurface) -> Result<Self, Self::Error> {
        match value {
            v1::TileSurface::Unspecified => Err((
                "invalid_enum",
                "TileSurface is UNSPECIFIED; sender must provide a concrete variant",
            )),
            v1::TileSurface::None => Ok(Self::None),
            v1::TileSurface::Street => Ok(Self::Street),
            v1::TileSurface::Bridge => Ok(Self::Bridge),
            v1::TileSurface::Rail => Ok(Self::Rail),
            v1::TileSurface::RailCrossing => Ok(Self::RailCrossing),
        }
    }
}

impl From<TileSurfaceDto> for v1::TileSurface {
    fn from(value: TileSurfaceDto) -> Self {
        match value {
            TileSurfaceDto::None => Self::None,
            TileSurfaceDto::Street => Self::Street,
            TileSurfaceDto::Bridge => Self::Bridge,
            TileSurfaceDto::Rail => Self::Rail,
            TileSurfaceDto::RailCrossing => Self::RailCrossing,
        }
    }
}

impl TryFrom<v1::TileCover> for TileCoverDto {
    type Error = ProtoConversionError;

    fn try_from(value: v1::TileCover) -> Result<Self, Self::Error> {
        match value {
            v1::TileCover::Unspecified => Err((
                "invalid_enum",
                "TileCover is UNSPECIFIED; sender must provide a concrete variant",
            )),
            v1::TileCover::None => Ok(Self::None),
            v1::TileCover::Building => Ok(Self::Building),
            v1::TileCover::Tree => Ok(Self::Tree),
            v1::TileCover::Detail => Ok(Self::Detail),
        }
    }
}

impl From<TileCoverDto> for v1::TileCover {
    fn from(value: TileCoverDto) -> Self {
        match value {
            TileCoverDto::None => Self::None,
            TileCoverDto::Building => Self::Building,
            TileCoverDto::Tree => Self::Tree,
            TileCoverDto::Detail => Self::Detail,
        }
    }
}

impl From<LayeredTileDto> for v1::LayeredTile {
    fn from(value: LayeredTileDto) -> Self {
        Self {
            local_index: u32::from(value.local_index),
            base: v1::TileBase::from(value.base) as i32,
            surface: v1::TileSurface::from(value.surface) as i32,
            cover: v1::TileCover::from(value.cover) as i32,
            display: value.display,
            zone_id: value.zone_id,
            road_mask: value.road_mask.map(u32::from),
            rail_mask: value.rail_mask.map(u32::from),
            version: value.version,
        }
    }
}

impl TryFrom<v1::LayeredTile> for LayeredTileDto {
    type Error = ProtoConversionError;

    fn try_from(value: v1::LayeredTile) -> Result<Self, Self::Error> {
        let base = v1::TileBase::try_from(value.base)
            .map_err(|_| ("invalid_enum", "LayeredTile.base out of range"))?;
        let surface = v1::TileSurface::try_from(value.surface)
            .map_err(|_| ("invalid_enum", "LayeredTile.surface out of range"))?;
        let cover = v1::TileCover::try_from(value.cover)
            .map_err(|_| ("invalid_enum", "LayeredTile.cover out of range"))?;
        let local_index = u16::try_from(value.local_index)
            .map_err(|_| ("invalid_field", "LayeredTile.local_index exceeds u16"))?;
        let road_mask = value
            .road_mask
            .map(u8::try_from)
            .transpose()
            .map_err(|_| ("invalid_field", "LayeredTile.road_mask exceeds u8"))?;
        let rail_mask = value
            .rail_mask
            .map(u8::try_from)
            .transpose()
            .map_err(|_| ("invalid_field", "LayeredTile.rail_mask exceeds u8"))?;

        Ok(Self {
            local_index,
            base: base.try_into()?,
            surface: surface.try_into()?,
            cover: cover.try_into()?,
            display: value.display,
            zone_id: value.zone_id,
            road_mask,
            rail_mask,
            version: value.version,
        })
    }
}

impl From<v1::ChunkCoord> for ChunkCoordDto {
    fn from(c: v1::ChunkCoord) -> Self {
        ChunkCoordDto { x: c.x, y: c.y }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Most serde-based DTOs were stripped in Task 7 (binary protobuf wire).
    // Wire-format correctness is now covered by the `proto_roundtrip_tests`
    // module below. The remaining JSON-shape test covers ChunkSnapshotDto,
    // which is still on the JSONB persistence path.

    #[test]
    fn chunk_snapshot_round_trips_through_jsonb_shape() {
        // ChunkSnapshotDto is persisted as JSONB in the snapshots table.
        let dto = ChunkSnapshotDto {
            protocol_version: PROTOCOL_VERSION,
            world_id: WorldId("abutown-main".to_string()),
            coord: ChunkCoordDto { x: 1, y: 2 },
            chunk_state: ChunkStateDto::Active,
            chunk_version: 7,
            tile_count: 1,
            tiles: vec![LayeredTileDto {
                local_index: 11,
                base: TileBaseDto::Grass,
                surface: TileSurfaceDto::Street,
                cover: TileCoverDto::None,
                display: None,
                zone_id: None,
                road_mask: Some(5),
                rail_mask: None,
                version: 7,
            }],
        };
        let json = serde_json::to_string(&dto).unwrap();
        let back: ChunkSnapshotDto = serde_json::from_str(&json).unwrap();
        assert_eq!(dto, back);
    }

    #[test]
    fn layered_tile_proto_round_trips() {
        let tile = LayeredTileDto {
            local_index: 7,
            base: TileBaseDto::Riverbank,
            surface: TileSurfaceDto::Bridge,
            cover: TileCoverDto::None,
            display: None,
            zone_id: Some("zone:limmat-river".to_string()),
            road_mask: Some(10),
            rail_mask: None,
            version: 3,
        };

        let proto: v1::LayeredTile = tile.clone().into();
        let back = LayeredTileDto::try_from(proto).expect("valid layered tile");

        assert_eq!(back, tile);
    }

    #[test]
    fn chunk_snapshot_uses_layered_tiles() {
        let snapshot = ChunkSnapshotDto {
            protocol_version: PROTOCOL_VERSION,
            world_id: WorldId("abutown-main".to_string()),
            coord: ChunkCoordDto { x: 1, y: 2 },
            chunk_state: ChunkStateDto::Active,
            chunk_version: 5,
            tile_count: 1024,
            tiles: vec![LayeredTileDto {
                local_index: 0,
                base: TileBaseDto::Grass,
                surface: TileSurfaceDto::Street,
                cover: TileCoverDto::None,
                display: None,
                zone_id: None,
                road_mask: Some(5),
                rail_mask: None,
                version: 1,
            }],
        };

        assert_eq!(snapshot.tiles[0].surface, TileSurfaceDto::Street);
    }
}

#[cfg(test)]
mod proto_roundtrip_tests {
    use super::v1::*;
    use prost::Message;

    fn sample_chunk() -> ChunkCoord {
        ChunkCoord { x: 4, y: 4 }
    }
    fn sample_world_coord() -> WorldCoord {
        WorldCoord { x: 100.0, y: 200.0 }
    }

    fn assert_roundtrip<M: Message + Default + PartialEq + std::fmt::Debug>(msg: &M) {
        let bytes = msg.encode_to_vec();
        let back = M::decode(bytes.as_slice()).expect("decode");
        assert_eq!(&back, msg);
    }

    #[test]
    fn roundtrip_hello() {
        let msg = ServerMessage {
            body: Some(server_message::Body::Hello(Hello {
                protocol_version: 16,
                world_id: "abutown-main".into(),
                chunk_size: 32,
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_tile_pulse() {
        let msg = ServerMessage {
            body: Some(server_message::Body::TilePulse(TilePulse {
                protocol_version: 16,
                world_id: "abutown-main".into(),
                tick: 1234,
                version: 5678,
                coord: Some(sample_chunk()),
                local_index: 11,
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_mobility_chunk_delta() {
        let agent = AgentMobility {
            id: "agent:a:1".into(),
            state: Some(AgentState {
                state: Some(agent_state::State::Walking(Walking {
                    link_id: "link:a".into(),
                    progress: 0.5,
                })),
            }),
            world_coord: Some(sample_world_coord()),
            direction: Direction::E as i32,
            sprite_key: "pedestrian:5".into(),
            plan_cursor: 0,
        };
        let msg = ServerMessage {
            body: Some(server_message::Body::MobilityChunkDelta(
                MobilityChunkDelta {
                    protocol_version: 16,
                    world_id: "abutown-main".into(),
                    tick: 100,
                    chunk: Some(sample_chunk()),
                    changed_agents: vec![agent],
                    changed_vehicles: vec![],
                    left_agents: vec!["agent:gone:1".into()],
                    left_vehicles: vec![],
                },
            )),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_mobility_chunk_snapshot() {
        let msg = ServerMessage {
            body: Some(server_message::Body::MobilityChunkSnapshot(
                MobilityChunkSnapshot {
                    protocol_version: 16,
                    world_id: "abutown-main".into(),
                    tick: 100,
                    chunk: Some(sample_chunk()),
                    agents: vec![],
                    vehicles: vec![],
                },
            )),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_chunk_subscribe() {
        let msg = ClientMessage {
            body: Some(client_message::Body::ChunkSubscribe(ChunkSubscribe {
                protocol_version: 16,
                coords: vec![sample_chunk(), ChunkCoord { x: 5, y: 4 }],
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_chunk_unsubscribe() {
        let msg = ClientMessage {
            body: Some(client_message::Body::ChunkUnsubscribe(ChunkUnsubscribe {
                protocol_version: 16,
                coords: vec![sample_chunk()],
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_command_response_accepted() {
        let msg = CommandResponse {
            outcome: Some(command_response::Outcome::Accepted(CommandAccepted {
                protocol_version: 16,
                world_id: "abutown-main".into(),
                command_id: "cmd:1".into(),
                event: Some(WorldEvent {}),
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_command_response_rejected() {
        let msg = CommandResponse {
            outcome: Some(command_response::Outcome::Rejected(CommandRejected {
                protocol_version: 16,
                world_id: "abutown-main".into(),
                command_id: "cmd:1".into(),
                code: "invalid_coord".into(),
                message: "coord out of range".into(),
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_server_error() {
        let msg = ServerMessage {
            body: Some(server_message::Body::Error(ServerError {
                protocol_version: 16,
                world_id: "abutown-main".into(),
                code: "internal".into(),
                message: "tick task gone".into(),
            })),
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_world_summary() {
        let msg = WorldSummary {
            protocol_version: 16,
            world_id: "abutown-main".into(),
            chunk_size: 32,
            loaded_chunks: vec![sample_chunk(), ChunkCoord { x: 5, y: 4 }],
            tick_period_ms: 100,
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_chunk_snapshot() {
        let msg = ChunkSnapshot {
            protocol_version: 16,
            world_id: "abutown-main".into(),
            coord: Some(sample_chunk()),
            chunk_version: 5,
            chunk_state: ChunkState::Active as i32,
            tile_count: 1024,
            tiles: vec![LayeredTile {
                local_index: 0,
                base: TileBase::Grass as i32,
                surface: TileSurface::Street as i32,
                cover: TileCover::None as i32,
                display: None,
                zone_id: None,
                road_mask: Some(5),
                rail_mask: None,
                version: 1,
            }],
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn roundtrip_health_response() {
        let msg = HealthResponse {
            protocol_version: 16,
            service: "abutown-sim".into(),
            world_id: "abutown-main".into(),
            ok: true,
        };
        assert_roundtrip(&msg);
    }

    #[test]
    fn unknown_field_is_ignored() {
        // Encode a MobilityChunkDelta and decode as Hello. The shared first
        // two tags (protocol_version u32, world_id string) are compatible
        // and decode correctly; all higher tags in MobilityChunkDelta are
        // unknown to Hello and prost must silently skip them.
        let delta = MobilityChunkDelta {
            protocol_version: 16,
            world_id: "abutown-main".into(),
            tick: 100,
            chunk: Some(sample_chunk()),
            changed_agents: vec![],
            changed_vehicles: vec![],
            left_agents: vec![],
            left_vehicles: vec![],
        };
        let bytes = delta.encode_to_vec();
        let back = Hello::decode(bytes.as_slice()).expect("decode tolerates unknown fields");
        assert_eq!(back.protocol_version, 16);
        assert_eq!(back.world_id, "abutown-main");
        assert_eq!(back.chunk_size, 100);
    }
}
