// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file abutown.proto (package abutown.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file abutown.proto.
 */
export const file_abutown: GenFile = /*@__PURE__*/
  fileDesc("Cg1hYnV0b3duLnByb3RvEgphYnV0b3duLnYxIhcKBFBpbmcSDwoHbWVzc2FnZRgBIAEoCWIGcHJvdG8z");

/**
 * Placeholder schema. The previous simulation's messages were removed when the
 * app was stripped to the card hand (see
 * docs/superpowers/specs/2026-07-01-strip-to-cardhand-design.md). This single
 * message keeps the buf + prost-build + protoc-gen-es toolchain wired and
 * provably working, ready for the next simulation's messages. Recover the old
 * schema from git history if needed.
 *
 * @generated from message abutown.v1.Ping
 */
export type Ping = Message<"abutown.v1.Ping"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message abutown.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_abutown, 0);
