// Phase 7b browser smoke: verify per-chunk wire protocol over the new
// binary protobuf transport.
//
// Asserts:
// - Initial subscribe emits ≥1 mobility_chunk_snapshot per subscribed chunk.
// - Per-tick mobility_chunk_delta frames flow for subscribed chunks.
// - Idle (no pan, no zoom) eventually quiets down.
// - Pan triggers new chunk_subscribe → new snapshots.
// - Zero text frames received (the wire is binary post-migration).

import { chromium } from '@playwright/test';
import { fromBinary } from '@bufbuild/protobuf';
// The proto schemas live in a .ts file (gitignored, generated by buf). We can't
// import it from a plain .mjs at module-evaluation time without a TS loader,
// and a global tsx/esm loader breaks Playwright's CJS package.json require.
// Use tsx's programmatic ESM hook activated only for this dynamic import.
import { tsImport } from 'tsx/esm/api';
const protoModule = await tsImport('../src/backend/proto/abutown_pb.ts', import.meta.url);
const { ClientMessageSchema, ServerMessageSchema } = protoModule;

const URL = 'http://127.0.0.1:5175';
const PAGE_TIMEOUT_MS = 15000;

async function pause(ms) { await new Promise((r) => setTimeout(r, ms)); }

function toBytes(payload) {
  if (payload instanceof Buffer) {
    return new Uint8Array(payload.buffer, payload.byteOffset, payload.byteLength);
  }
  if (payload instanceof ArrayBuffer) return new Uint8Array(payload);
  if (payload instanceof Uint8Array) return payload;
  return null;
}

const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1024, height: 768 } });
const page = await context.newPage();

const sentBinary = [];
const receivedBinary = [];
const textFramesSentSamples = [];
const textFramesReceivedSamples = [];
let textFramesSent = 0;
let textFramesReceived = 0;
const consoleErrors = [];

page.on('websocket', (ws) => {
  // Filter to the backend WS only. The vite dev server also exposes an HMR
  // socket on port 5175 that exchanges text frames (e.g. {"type":"connected"})
  // — those are noise for this smoke.
  if (!ws.url().includes(':8080/')) return;
  ws.on('framesent', (ev) => {
    if (typeof ev.payload === 'string') {
      textFramesSent += 1;
      if (textFramesSentSamples.length < 3) textFramesSentSamples.push(ev.payload.slice(0, 200));
      return;
    }
    const bytes = toBytes(ev.payload);
    if (bytes) sentBinary.push(bytes);
  });
  ws.on('framereceived', (ev) => {
    if (typeof ev.payload === 'string') {
      textFramesReceived += 1;
      if (textFramesReceivedSamples.length < 3) textFramesReceivedSamples.push(ev.payload.slice(0, 200));
      return;
    }
    const bytes = toBytes(ev.payload);
    if (bytes) receivedBinary.push(bytes);
  });
});
page.on('console', (msg) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
page.on('pageerror', (err) => consoleErrors.push(err.message));

try {
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: PAGE_TIMEOUT_MS });
} catch (e) {
  console.log(JSON.stringify({ status: 'page-load-failed', error: String(e) }, null, 2));
  await browser.close();
  process.exit(1);
}

// Let WS open + initial subscribe poll fire (200 ms interval).
await pause(2500);
const initialReceivedCount = receivedBinary.length;

// Pan camera ~250 px left to add new chunks on the right edge of view.
await page.mouse.move(512, 384);
await page.mouse.down();
for (let dx = 0; dx <= 250; dx += 25) {
  await page.mouse.move(512 - dx, 384);
  await pause(15);
}
await page.mouse.up();
await pause(2000);
const afterPanReceivedCount = receivedBinary.length;

// Settle: 1.5 s idle, see how many frames per second arrive.
const idleStart = receivedBinary.length;
await pause(1500);
const idleEnd = receivedBinary.length;

await browser.close();

function decodeServer(bytes) {
  try { return fromBinary(ServerMessageSchema, bytes); } catch { return null; }
}
function decodeClient(bytes) {
  try { return fromBinary(ClientMessageSchema, bytes); } catch { return null; }
}

const receivedMessages = receivedBinary.map(decodeServer).filter(Boolean);
const sentMessages = sentBinary.map(decodeClient).filter(Boolean);

function summariseReceived(messages) {
  const out = {
    hello: 0,
    tile_pulse: 0,
    mobility_chunk_snapshot: { count: 0, chunks: {} },
    mobility_chunk_delta: { count: 0, chunks: {} },
    world_event: 0,
    error: 0,
    other: 0,
  };
  for (const m of messages) {
    switch (m.body.case) {
      case 'hello': out.hello += 1; break;
      case 'tilePulse': out.tile_pulse += 1; break;
      case 'mobilityChunkSnapshot': {
        out.mobility_chunk_snapshot.count += 1;
        const c = m.body.value.chunk;
        const k = `${c?.x ?? '?'},${c?.y ?? '?'}`;
        out.mobility_chunk_snapshot.chunks[k] = (out.mobility_chunk_snapshot.chunks[k] ?? 0) + 1;
        break;
      }
      case 'mobilityChunkDelta': {
        out.mobility_chunk_delta.count += 1;
        const c = m.body.value.chunk;
        const k = `${c?.x ?? '?'},${c?.y ?? '?'}`;
        out.mobility_chunk_delta.chunks[k] = (out.mobility_chunk_delta.chunks[k] ?? 0) + 1;
        break;
      }
      case 'worldEvent': out.world_event += 1; break;
      case 'error': out.error += 1; break;
      default: out.other += 1;
    }
  }
  return out;
}

function summariseSent(messages) {
  const out = { chunk_subscribe: 0, chunk_unsubscribe: 0, other: 0 };
  for (const m of messages) {
    if (m.body.case === 'chunkSubscribe') out.chunk_subscribe += 1;
    else if (m.body.case === 'chunkUnsubscribe') out.chunk_unsubscribe += 1;
    else out.other += 1;
  }
  return out;
}

const recv = summariseReceived(receivedMessages);
const sent = summariseSent(sentMessages);

const clientReceivesEntityData = receivedMessages.some((m) => {
  if (m.body.case === 'mobilityChunkSnapshot') {
    return m.body.value.agents.length > 0 || m.body.value.vehicles.length > 0;
  }
  if (m.body.case === 'mobilityChunkDelta') {
    return m.body.value.changedAgents.length > 0 || m.body.value.changedVehicles.length > 0;
  }
  return false;
});

const checks = {
  page_loaded: receivedBinary.length > 0,
  got_chunk_snapshots_on_subscribe: recv.mobility_chunk_snapshot.count > 0,
  one_snapshot_per_subscribed_chunk:
    Object.keys(recv.mobility_chunk_snapshot.chunks).length >= 9, // at least 3×3 visible area
  got_chunk_deltas_per_tick: recv.mobility_chunk_delta.count > 0,
  client_receives_entity_data: clientReceivesEntityData,
  // The wire is binary post-migration: zero text frames in either direction.
  no_text_frames: textFramesReceived === 0 && textFramesSent === 0,
  client_sent_chunk_subscribe: sent.chunk_subscribe > 0,
  pan_added_more_frames: afterPanReceivedCount > initialReceivedCount,
  no_console_errors: consoleErrors.length === 0,
};

const summary = {
  status: Object.values(checks).every(Boolean) ? 'ok' : 'failed',
  url: URL,
  totals: {
    received_frames: receivedBinary.length,
    sent_frames: sentBinary.length,
    text_frames_received: textFramesReceived,
    text_frames_sent: textFramesSent,
    text_frames_received_samples: textFramesReceivedSamples,
    text_frames_sent_samples: textFramesSentSamples,
  },
  phases: {
    after_open_2500ms: initialReceivedCount,
    after_pan: afterPanReceivedCount,
    idle_1500ms_frames: idleEnd - idleStart,
  },
  sent_breakdown: sent,
  received_breakdown: recv,
  checks,
  console_errors: consoleErrors,
};

console.log(JSON.stringify(summary, null, 2));
process.exit(summary.status === 'ok' ? 0 : 1);
