import { createAssetPack, type AssetFrame, type AssetRole } from './assetPack';

export const PAK128_REVISION = 'acdf2f0793a6beee5ea34ea85d308fbbeccf50c5';
export const PAK128_REQUIRED_ROLES = [
  'terrain.grass',
  'terrain.water',
  'terrain.riverbank',
  'road.straight',
  'road.curve',
  'road.intersection',
  'road.bridge',
  'rail.straight',
  'rail.station',
  'building.residential.low',
  'building.commercial.mid',
  'building.civic',
  'building.industrial',
  'vegetation.tree',
  'detail.park',
  'detail.industry',
  'detail.dock',
  'detail.quay',
  'vehicle.bus',
  'vehicle.truck',
  'vehicle.train.engine',
  'vehicle.train.wagon',
  'agent.pedestrian',
] as const satisfies readonly AssetRole[];

const ROOT = '/simutrans-assets/pak128';

const provenance = (sourcePath: string, datPath: string) => ({
  sourcePath,
  datPath,
  license: 'Artistic-2.0' as const,
  revision: PAK128_REVISION,
});

const cell = (row: number, col: number, height = 128) => ({ x: col * 128, y: row * 128, width: 128, height });

const pak128Assets: AssetFrame[] = [
  {
    role: 'terrain.grass',
    path: `${ROOT}/landscape/grounds/texture-climate.png`,
    source: { x: 0, y: 0, width: 128, height: 64 },
    anchor: { x: 64, y: 32 },
    baseline: 32,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('landscape/grounds/texture-climate.png', 'landscape/grounds/texture-climate.dat'),
  },
  {
    role: 'terrain.water',
    path: `${ROOT}/landscape/grounds/water_ani.png`,
    source: cell(1, 0, 64),
    anchor: { x: 64, y: 32 },
    baseline: 32,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('landscape/grounds/water_ani.png', 'landscape/grounds/water_ani.dat'),
  },
  {
    role: 'terrain.riverbank',
    path: `${ROOT}/landscape/rivers/rivers.png`,
    source: cell(1, 1),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('landscape/rivers/rivers.png', 'landscape/rivers/rivers.dat'),
  },
  {
    role: 'road.straight',
    path: `${ROOT}/infrastructure/roads/cityroad_030.png`,
    source: cell(1, 5),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/roads/cityroad_030.png', 'infrastructure/roads/cityroad_030.dat'),
  },
  {
    role: 'road.curve',
    path: `${ROOT}/infrastructure/roads/cityroad_030.png`,
    source: cell(2, 4),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/roads/cityroad_030.png', 'infrastructure/roads/cityroad_030.dat'),
  },
  {
    role: 'road.intersection',
    path: `${ROOT}/infrastructure/roads/cityroad_030.png`,
    source: cell(2, 3),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/roads/cityroad_030.png', 'infrastructure/roads/cityroad_030.dat'),
  },
  {
    role: 'road.bridge',
    path: `${ROOT}/infrastructure/road_bridges/road_040_bridge.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/road_bridges/road_040_bridge.png', 'infrastructure/road_bridges/road_040_bridge.dat'),
  },
  {
    role: 'rail.straight',
    path: `${ROOT}/infrastructure/rail_tracks/rail_120_tracks.png`,
    source: cell(1, 5),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/rail_tracks/rail_120_tracks.png', 'infrastructure/rail_tracks/rail_120_tracks.dat'),
  },
  {
    role: 'rail.station',
    path: `${ROOT}/infrastructure/rail_stations/station_03_02.png`,
    source: cell(1, 2),
    anchor: { x: 64, y: 96 },
    baseline: 96,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/rail_stations/station_03_02.png', 'infrastructure/rail_stations/station_03_02.dat'),
  },
  {
    role: 'building.residential.low',
    path: `${ROOT}/cityhouses/res/res_08_47.png`,
    source: cell(2, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('cityhouses/res/res_08_47.png', 'cityhouses/res/res_08_47.dat'),
  },
  {
    role: 'building.commercial.mid',
    path: `${ROOT}/cityhouses/com/com_09_18.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('cityhouses/com/com_09_18.png', 'cityhouses/com/com_09_18.dat'),
  },
  {
    role: 'building.civic',
    path: `${ROOT}/special_buildings/city/justice.png`,
    source: cell(2, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('special_buildings/city/justice.png', 'special_buildings/city/justice.dat'),
  },
  {
    role: 'building.industrial',
    path: `${ROOT}/cityhouses/ind/ind_00_03.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('cityhouses/ind/ind_00_03.png', 'cityhouses/ind/ind_00_03.dat'),
  },
  {
    role: 'vegetation.tree',
    path: `${ROOT}/landscape/trees/tree020.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 0.78,
    cleanup: 'pak128',
    provenance: provenance('landscape/trees/tree020.png', 'landscape/trees/tree020.dat'),
  },
  {
    role: 'detail.park',
    path: `${ROOT}/special_buildings/city/french_park_1.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 64 },
    baseline: 64,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('special_buildings/city/french_park_1.png', 'special_buildings/city/french_park_1.dat'),
  },
  {
    role: 'detail.industry',
    path: `${ROOT}/factories/modern_fuel_station.png`,
    source: cell(0, 2),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('factories/modern_fuel_station.png', 'factories/modern_fuel_station.dat'),
  },
  {
    role: 'detail.dock',
    path: `${ROOT}/infrastructure/water_all/bulk_dock.png`,
    source: cell(2, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/water_all/bulk_dock.png', 'infrastructure/water_all/bulk_dock.dat'),
  },
  {
    role: 'detail.quay',
    path: `${ROOT}/infrastructure/water_all/crate_goods_dock.png`,
    source: cell(2, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 1,
    cleanup: 'pak128',
    provenance: provenance('infrastructure/water_all/crate_goods_dock.png', 'infrastructure/water_all/crate_goods_dock.dat'),
  },
  {
    role: 'vehicle.bus',
    path: `${ROOT}/vehicles/road-psg+mail/man_lions_city.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 88 },
    baseline: 88,
    scale: 0.42,
    cleanup: 'pak128',
    direction: 'W',
    provenance: provenance('vehicles/road-psg+mail/man_lions_city.png', 'vehicles/road-psg+mail/man_lions_city.dat'),
  },
  {
    role: 'vehicle.truck',
    path: `${ROOT}/vehicles/road-cargo/goods_truck_0.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 88 },
    baseline: 88,
    scale: 0.42,
    cleanup: 'pak128',
    direction: 'W',
    provenance: provenance('vehicles/road-cargo/goods_truck_0.png', 'vehicles/road-cargo/goods_truck_0.dat'),
  },
  {
    role: 'vehicle.train.engine',
    path: `${ROOT}/vehicles/rail-engines/rvg-d41-tubus.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 88 },
    baseline: 88,
    scale: 0.52,
    cleanup: 'pak128',
    direction: 'W',
    provenance: provenance('vehicles/rail-engines/rvg-d41-tubus.png', 'vehicles/rail-engines/rvg-d41-tubus.dat'),
  },
  {
    role: 'vehicle.train.wagon',
    path: `${ROOT}/vehicles/rail-psg+mail/rvg_tigress_wagon.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 88 },
    baseline: 88,
    scale: 0.52,
    cleanup: 'pak128',
    direction: 'W',
    provenance: provenance('vehicles/rail-psg+mail/rvg_tigress_wagon.png', 'vehicles/rail-psg+mail/rvg_tigress_wagon.dat'),
  },
  {
    role: 'agent.pedestrian',
    path: `${ROOT}/base/pedestrians/privat-pedestrians-128.png`,
    source: cell(1, 0),
    anchor: { x: 64, y: 116 },
    baseline: 116,
    scale: 0.96,
    cleanup: 'pak128',
    direction: 'S',
    provenance: provenance('base/pedestrians/privat-pedestrians-128.png', 'base/pedestrians/Pedestrians.dat'),
  },
];

export const pak128AssetPack = createAssetPack({
  id: 'simutrans-pak128',
  tile: { width: 128, height: 64 },
  assets: pak128Assets,
});

for (const role of PAK128_REQUIRED_ROLES) pak128AssetPack.require(role);
